=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/tas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com"	xmlns="http://www.w3schools.com" elementFormDefault="qualified">
   <xsd:element name="program">
      <xsd:complexType>
         <xsd:all>
            <xsd:element ref="threads" minOccurs="1" maxOccurs="1" />
            <xsd:element ref="tas_taskparallelisms" minOccurs="0" maxOccurs="1" />
            <xsd:element ref="tas_dataparallelisms" minOccurs="0" maxOccurs="1" />
            <xsd:element ref="tas_pipelineparallelisms" minOccurs="0" maxOccurs="1"  />
            <xsd:element ref="csections" minOccurs="0" maxOccurs="1" />
         </xsd:all>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name="threads">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="thread" maxOccurs="unbounded">
               <xsd:complexType>
                  <xsd:simpleContent>
                     <xsd:extension base="xsd:string">
                        <xsd:attribute name="cluster" type="xsd:int" use="required" />
                        <xsd:attribute name="core" type="xsd:int" use="required" />
                        <xsd:attribute name="id" type="xsd:string" use="required" />
                        <xsd:attribute name="routine" type="xsd:string" use="required" />
                     </xsd:extension>
                  </xsd:simpleContent>
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:complexType name="parallelism">
      <xsd:sequence>
         <xsd:element name="threads" minOccurs="1" maxOccurs="1">
            <xsd:complexType>
               <xsd:sequence>
                  <xsd:element name="thread" maxOccurs="unbounded">
                     <xsd:complexType>
                        <xsd:simpleContent>
                           <xsd:extension base="xsd:string">
                              <xsd:attribute name="ref" type="xsd:string" use="required" />
                              <xsd:attribute name="main" type="xsd:int" />
                           </xsd:extension>
                        </xsd:simpleContent>
                     </xsd:complexType>
                  </xsd:element>
               </xsd:sequence>
            </xsd:complexType>
         </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" use="required" />
      <xsd:attribute name="init_id" type="xsd:string" use="optional" />
      <xsd:attribute name="finalize_id" type="xsd:string" use="optional" />
	  <xsd:attribute name="description" type="xsd:string" use="required" />
      <xsd:attribute name="main_as_worker" type="xsd:int" use="required" />
      <xsd:attribute name="called_by" type="xsd:IDREF" default="BEGIN"/>
      <xsd:attribute name="executed_after" type="xsd:IDREF"/>
   </xsd:complexType>
   
   
   <xsd:element name="tas_taskparallelisms">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="tas_taskparallelism" maxOccurs="unbounded" type="tas_taskparallelism" />
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="tas_taskparallelism">
      <xsd:complexContent>
         <xsd:extension base="parallelism">
            <xsd:sequence>
               <xsd:element name="tasks" minOccurs="1" maxOccurs="1">
                  <xsd:complexType>
                     <xsd:sequence>
                        <xsd:element name="task" maxOccurs="unbounded">
                           <xsd:complexType>
                              <xsd:simpleContent>
                                 <xsd:extension base="xsd:string">
                                    <xsd:attribute name="function" type="xsd:string" use="required" />
                                    <xsd:attribute name="thread" type="xsd:string" use="required" />
                                 </xsd:extension>
                              </xsd:simpleContent>
                           </xsd:complexType>
                        </xsd:element>
                     </xsd:sequence>
                  </xsd:complexType>
               </xsd:element>
            </xsd:sequence>
         </xsd:extension>
      </xsd:complexContent>   
   </xsd:complexType>

   <xsd:element name="tas_dataparallelisms">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="tas_dataparallelism" maxOccurs="unbounded" type="tas_dataparallelism" />
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="tas_dataparallelism">
      <xsd:complexContent>
         <xsd:extension base="parallelism">
            <xsd:sequence>
               <xsd:element name="task" minOccurs="1" maxOccurs="1">
                  <xsd:complexType>
                     <xsd:simpleContent>
                        <xsd:extension base="xsd:string">
                           <xsd:attribute name="function" type="xsd:string" use="required" />
                        </xsd:extension>
                     </xsd:simpleContent>
                  </xsd:complexType>
               </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="nr_args" type="xsd:int" use="required" />
         </xsd:extension>
      </xsd:complexContent>
   </xsd:complexType>
               
   <xsd:element name="tas_pipelineparallelisms">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="tas_pipelineparallelism" maxOccurs="unbounded" type="tas_pipelineparallelism" />
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="tas_pipelineparallelism">
      <xsd:complexContent>
         <xsd:extension base="parallelism">
            <xsd:sequence>
               <xsd:element name="tasks" minOccurs="1" maxOccurs="1">
                  <xsd:complexType>
                     <xsd:sequence>
                        <xsd:element name="task" maxOccurs="unbounded">
                           <xsd:complexType>
                              <xsd:simpleContent>
                                 <xsd:extension base="xsd:string">
                                    <xsd:attribute name="function" type="xsd:string" use="required" />
                                 </xsd:extension>
                              </xsd:simpleContent>
                           </xsd:complexType>
                        </xsd:element>
                     </xsd:sequence>
                  </xsd:complexType>
               </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="iterations" type="xsd:int" use="required" />
         </xsd:extension>
      </xsd:complexContent>
   </xsd:complexType>
            
   <xsd:element name="csections">
      <xsd:complexType>
         <xsd:sequence>   
            <xsd:element name="csection" minOccurs="0" maxOccurs="unbounded">
               <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="thread" minOccurs="1" maxOccurs="1">
                        <xsd:complexType>
                           <xsd:simpleContent>
                              <xsd:extension base="xsd:string">
                                 <xsd:attribute name="id" type="xsd:string" use="required" />
                              </xsd:extension>
                           </xsd:simpleContent>
                        </xsd:complexType>
                     </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="id" type="xsd:string" use="required" />
                  <xsd:attribute name="description" type="xsd:string" use="required" />
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
      </xsd:complexType>   
   </xsd:element>
   
</xsd:schema>

=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/input_composed_for_dtd.xml
<?xml version="1.0"?>
<!-- DOCTYPE program SYSTEM "tas_annotations.dtd" -->
<program xsi:schemaLocation="http://www.w3schools.com tas.xsd" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <threads>
        <thread cluster="0" core="1" id="1" routine="main"/>
        <thread cluster="0" core="2" id="2" routine="tas_thread"/>
        <thread cluster="0" core="3" id="3" routine="tas_thread"/>
        <thread cluster="0" core="4" id="4" routine="tas_thread"/>
        <thread cluster="0" core="5" id="5" routine="tas_thread"/>
    </threads>
    <tas_taskparallelisms>
        <tas_taskparallelism id="A" description="A Task Parallelism" main_as_worker="1" >
            <threads>
                <thread ref="1" main="1"/>
                <thread ref="2"/>
                <thread ref="3"/>
            </threads>
            <tasks>
                <task function="foo_1" thread="1"/>
                <task function="foo_2" thread="2"/>
            </tasks>
        </tas_taskparallelism>
      
        <tas_taskparallelism id="D" description="D Task Parallelism" main_as_worker="1" called_by="A" >
            <threads>
                <thread ref="2" main="1"/>
                <thread ref="4"/>
            </threads>
            <tasks>
                <task function="bar_2" thread="2"/>
                <task function="bar_4" thread="4"/>
                <task function="bar_5" thread="5"/>
            </tasks>
        </tas_taskparallelism>
      
        <tas_taskparallelism id="E" description="E Task Parallelism" main_as_worker="1" executed_after="D" >
            <threads>
                <thread ref="2" main="1"/>
                <thread ref="5"/>
            </threads>
            <tasks>
                <task function="bar_2" thread="2"/>
                <task function="bar_5" thread="5"/>
            </tasks>
        </tas_taskparallelism>
    </tas_taskparallelisms>
    <tas_dataparallelisms>
        <tas_dataparallelism id="tas_pipeline_step_tp" description="Data Parallelism for step 2 in Pipeline" main_as_worker="1" nr_args="4" called_by="tas_pipeline_fft" executed_after="D" init_id="foo" finalize_id="bar"  init_id="foo" finalize_id="bar" >
            <threads>
                <thread ref="4" main="1"/>
                <thread ref="5"/>
                <thread ref="6"/>
                <thread ref="7"/>
            </threads>
            <task function="a_to_A_sub"/>
        </tas_dataparallelism>
    </tas_dataparallelisms>
    <tas_pipelineparallelisms>
        <tas_pipelineparallelism id="tas_pipeline_fft" description="Parallel FFT calculation with pipeline" main_as_worker="1" iterations="25" called_by="tas_pipeline_fft" executed_after="D"  init_id="foo" finalize_id="bar">
            <threads>
                <thread ref="0" main="1"/>
                <thread ref="1"/>
                <thread ref="2"/>
                <thread ref="3"/>
                <thread ref="4"/>
            </threads>
            <tasks>
                <task function="create_fft_input"/>
                <task function="a_to_A"/>
                <task function="AB_to_C"/>
                <task function="C_to_D"/>
                <task function="D_to_d"/>
            </tasks>
        </tas_pipelineparallelism>
    </tas_pipelineparallelisms>
</program>

=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/InputTaskParallelism.xml
<?xml version="1.0"?>
<program xsi:schemaLocation="http://www.w3schools.com tas.xsd" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <threads>
      <thread cluster="0" core="0" id="0" routine="main"/>
      <thread cluster="0" core="1" id="1" routine="tas_thread"/>
      <thread cluster="1" core="0" id="2" routine="tas_thread"/>
      <thread cluster="1" core="1" id="3" routine="tas_thread"/>
   </threads>
   <tas_taskparallelisms>
      <tas_taskparallelism id="tas_tp_main_loop_tp" description="Task Parallelism in pedal_to_medal" main_as_worker="1">
         <threads>
            <thread ref="0" main="1"/>
            <thread ref="1"/>
         </threads>
         <tasks>
            <task function="chassis" thread="0"/>
            <task function="shovel" thread="1"/>
         </tasks>
      </tas_taskparallelism>
      <tas_taskparallelism id="tas_tp_shovel_tp" description="Moving joints in parallel" main_as_worker="1" called_by="tas_tp_main_loop_tp">
         <threads>
            <thread ref="1" main="1"/>
            <thread ref="2"/>
            <thread ref="3"/>
         </threads>
         <tasks>
            <task function="joint_a" thread="1"/>
            <task function="joint_b" thread="2"/>
            <task function="joint_c" thread="3"/>
         </tasks>
      </tas_taskparallelism>
   </tas_taskparallelisms>
</program>

=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/nacheinander.xml
<?xml version="1.0"?>
<!DOCTYPE program SYSTEM "tas_annotations.dtd">
<program xsi:schemaLocation="http://www.w3schools.com tas.xsd" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <threads>
      <thread cluster="0" core="1" id="1" routine="main"/>
      <thread cluster="0" core="2" id="2" routine="tas_thread"/>
      <thread cluster="0" core="3" id="3" routine="tas_thread"/>
      <thread cluster="0" core="4" id="4" routine="tas_thread"/>
      <thread cluster="0" core="5" id="5" routine="tas_thread"/>
   </threads>
   <tas_taskparallelisms>
      <tas_taskparallelism id="A" description="A Task Parallelism" main_as_worker="1">
         <threads>
            <thread ref="1" main="1"/>
            <thread ref="2"/>
            <thread ref="3"/>
         </threads>
         <tasks>
            <task function="foo_1" thread="1"/>
            <task function="foo_2" thread="2"/>
            <task function="foo_3" thread="3"/>
         </tasks>
      </tas_taskparallelism>
      
      <tas_taskparallelism id="B" description="B Task Parallelism" main_as_worker="1" executed_after="A">
         <threads>
            <thread ref="1" main="1"/>
            <thread ref="4"/>
            <thread ref="5"/>
         </threads>
         <tasks>
            <task function="bar_1" thread="3"/>
            <task function="bar_2" thread="4"/>
            <task function="bar_3" thread="5"/>
         </tasks>
      </tas_taskparallelism>

	</tas_taskparallelisms>
</program>

=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/InputPipelineParallelism.xml
<?xml version="1.0"?>
<program xsi:schemaLocation="http://www.w3schools.com tas.xsd" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <threads>
        <thread cluster="0" core="0" id="0" routine="demo_fft_init"/>
        <thread cluster="0" core="1" id="1" routine="tas_thread"/>
        <thread cluster="0" core="2" id="2" routine="tas_thread"/>
        <thread cluster="0" core="3" id="3" routine="tas_thread"/>
        <thread cluster="1" core="0" id="4" routine="tas_thread"/>
        <thread cluster="1" core="1" id="5" routine="tas_thread"/>
        <thread cluster="1" core="2" id="6" routine="tas_thread"/>
        <thread cluster="1" core="3" id="7" routine="tas_thread"/>
    </threads>
   <tas_dataparallelisms>
      <tas_dataparallelism id="tas_pipeline_step_tp" description="Data Parallelism for step 2 in Pipeline" main_as_worker="1" nr_args="4" called_by="tas_pipeline_fft">
         <threads>
            <thread ref="4" main="1"/>
            <thread ref="5"/>
            <thread ref="6"/>
            <thread ref="7"/>
         </threads>
         <task function="a_to_A_sub"/>
      </tas_dataparallelism>
   </tas_dataparallelisms>
    <tas_pipelineparallelisms>
        <tas_pipelineparallelism id="tas_pipeline_fft" description="Parallel FFT calculation with pipeline" main_as_worker="1" iterations="25">
            <threads>
                <thread ref="0" main="1"/>
                <thread ref="1"/>
                <thread ref="2"/>
                <thread ref="3"/>
                <thread ref="4"/>
            </threads>
            <tasks>
                <task function="create_fft_input"/>
                <task function="a_to_A"/>
                <task function="AB_to_C"/>
                <task function="C_to_D"/>
                <task function="D_to_d"/>
            </tasks>
        </tas_pipelineparallelism>
   </tas_pipelineparallelisms>
</program>

=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/verschachtelt_with_init_finalize.xml
<?xml version="1.0"?>
<!DOCTYPE program SYSTEM "tas_annotations.dtd">
<program xsi:schemaLocation="http://www.w3schools.com tas.xsd" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <threads>
      <thread cluster="0" core="1" id="1" routine="main"/>
      <thread cluster="0" core="2" id="2" routine="tas_thread"/>
      <thread cluster="0" core="3" id="3" routine="tas_thread"/>
      <thread cluster="0" core="4" id="4" routine="tas_thread"/>
      <thread cluster="0" core="5" id="5" routine="tas_thread"/>
   </threads>
   <tas_taskparallelisms>
      <tas_taskparallelism id="A" description="A Task Parallelism" main_as_worker="1" init_id="A_ini" finalize_id="A_finalize" >
         <threads>
            <thread ref="1" main="1"/>
            <thread ref="2"/>
            <thread ref="3"/>
         </threads>
         <tasks>
            <task function="foo_1" thread="1"/>
            <task function="foo_2" thread="2"/>
            <task function="foo_3" thread="3"/>
         </tasks>
      </tas_taskparallelism>
      
      <tas_taskparallelism id="D" description="D Task Parallelism" main_as_worker="1" called_by="A" init_id="D_ini" finalize_id="D_fin">
         <threads>
            <thread ref="2" main="1"/>
            <thread ref="4"/>
            <thread ref="5"/>
         </threads>
         <tasks>
            <task function="bar_2" thread="2"/>
            <task function="bar_4" thread="4"/>
            <task function="bar_5" thread="5"/>
         </tasks>
      </tas_taskparallelism>
      
      <tas_taskparallelism id="E" description="E Task Parallelism" main_as_worker="1" executed_after="D" init_id="E_ini" finalize_id="E_fin">
         <threads>
            <thread ref="2" main="1"/>
            <thread ref="4"/>
            <thread ref="5"/>
         </threads>
         <tasks>
            <task function="bar_2" thread="2"/>
            <task function="bar_4" thread="4"/>
            <task function="bar_5" thread="5"/>
         </tasks>
      </tas_taskparallelism>


	</tas_taskparallelisms>
</program>

=== parmerasa-uau/tas2otawa/Tas2OtawaConverter/src/test/resources/InputDataParallelism.xml
<?xml version="1.0"?>
<program xsi:schemaLocation="http://www.w3schools.com tas.xsd" xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <threads>
      <thread cluster="0" core="0" id="0" routine="demo_5_main_core_0"/>
      <thread cluster="0" core="1" id="1" routine="tas_thread"/>
      <thread cluster="1" core="0" id="2" routine="tas_thread"/>
      <thread cluster="1" core="1" id="3" routine="tas_thread"/>
      <thread cluster="2" core="0" id="4" routine="tas_thread"/>
      <thread cluster="2" core="1" id="5" routine="tas_thread"/>
      <thread cluster="3" core="0" id="6" routine="tas_thread"/>
      <thread cluster="3" core="1" id="7" routine="tas_thread"/>
   </threads>
   <tas_dataparallelisms>
      <tas_dataparallelism id="genetic_dp_execute" description="Genetic Algorithm" main_as_worker="1" nr_args="8">
         <threads>
            <thread ref="0" main="1"/>
            <thread ref="1"/>
            <thread ref="2"/>
            <thread ref="3"/>
            <thread ref="4"/>
            <thread ref="5"/>
            <thread ref="6"/>
            <thread ref="7"/>
         </threads>
         <task function="init_and_evaluate"/>
      </tas_dataparallelism>
   </tas_dataparallelisms>
   <csections>
      <!-- additional csection for random number generator -->
      <csection id="rando_lock" description="Random Number Generator">
         <thread id="0,1,2,3,4,5,6,7"/>
      </csection>
   </csections>
</program>
